export const SET_VENDORS = 'SET_VENDORS';
export const SET_SHIP_MANAGERS = 'SET_SHIP_MANAGERS';
// export const SET_SUMMARY = 'SET_SUMMARY';
export const SET_LOGOUT = 'SET_LOGOUT';
// export const SERVICES = 'SERVICES';
export const SERVICE_REQUESTS = 'SERVICE_REQUESTS';

export const APPROVE_VENDOR_REQUESTS = 'APPROVE_VENDOR_REQUESTS'
// export const SERVICE_REQUESTS_DATA = 'SERVICE_REQUESTS_DATA'



